# -*- coding: utf-8 -*-
"""FireFusion – Sprint 2: Synthetic Social Media Post Generator Script for Narrative Clustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdCNFhgHqAldQvnwushXQF9LZb5bN2iv

This Script generates a labelled synthetic dataset of social-media-style posts about bushfire
events in Victoria.

Each post is augmented with realistic social-media metadata (timestamp, likes,
retweets, platform, hashtags, location).


Following will be the data coloumn structure:

 Columns:
   * post_id            → unique ID for each post
   * text               → the synthetic post text
   * cluster            → which narrative cluster the post belongs to
   * label              → "misinformation" or "factual"
   * platform           → simulated social media platform
   * location_mentioned → Australian place name embedded in the post (if any)
   * timestamp          → simulated post date/time (2019–2024 fire seasons, aligning with the bushfire training data)
   * engagement_score   → simulated likes + shares proxy
   * username           → fake Australian username
   * Hashtags  → Hashtags



The posts will be generated based on potential "narrative clusters" which are thematic groups
of posts that share a common story or angle.

A narrative cluster is a recurring type of story or angle that circulates
on social media. For example, "arson conspiracy" posts all share the same
underlying claim — that fires were deliberately lit. Grouping posts this
way means the model can learn not just WHETHER a post is misinformation,
but WHAT KIND, which helps emergency managers respond more precisely.

# Setup/ Install Dependencies. Please Run these cells first:
"""

!pip install faker pandas

"""# SECTION 1 – IMPORTS"""

import random # random number generator
import warnings #supress non critical warning outputs
import itertools # tools for efficient template looping
from datetime import datetime, timedelta
from pathlib import Path
import numpy as np
import pandas as pd
from faker import Faker  # Generating fake but realistic  usernames
import uuid # Generates unique post IDs
import matplotlib.pyplot as plt # incase of data visualization

# REPRODUCIBILITY SEED - to ensure everyone gets the same dataset
SEED = 42
random.seed(SEED)
fake = Faker("en_AU")       # "en_AU" gives us Australian-flavoured names
fake.seed_instance(SEED)

"""# Section 2 : CONFIGURATION"""

CONFIG = {
    # How many posts to generate in total.
    # 2000 is a reasonable starting point for a proof-of-concept.
    # team can  increase this later if needed.
    "total_posts": 2000,

    # What fraction of posts should be misinformation vs factual.
    # kept ratio at 60/40 to reflect that misinformation tends to spread more actively during disaster events,
    # so there's naturally more of it online.
    "misinfo_ratio": 0.60,

    # Where the CSV will be saved.
    # In Google Colab, this saves to /content/ by default.
    "output_file": "firefusion_synthetic_posts.csv",

    # Simulated date range for post timestamps.
    # Using the 2019–2024 window to cover the catastrophic Black Summer
    # season and subsequent years aligning with the bushfire training dataset
    "date_start": datetime(2019, 10, 1),
    "date_end":   datetime(2024, 3, 31),

    # The platforms posts will be attributed to, and how often each appears.
    # Weights are rough estimates based on where AU bushfire content spreads
    # most — Facebook is dominant in Australian community groups (see Ref [2]).
    "platforms":         ["Facebook", "Twitter/X", "Reddit", "Instagram", "TikTok"],
    "platform_weights":  [0.40,        0.30,        0.15,     0.10,       0.05],
}

"""#Section 3 Word Banks  Templates

Templates below contain placeholder tokens like "location" or "agency".
These word banks are what gets swapped in when we fill a template.
"""

VIC_LOCATIONS = [
    "Gippsland", "East Gippsland", "Mallacoota", "Bairnsdale", "Orbost",
    "Heyfield", "Buchan", "Corryong", "Mount Beauty", "Omeo",
    "Kinglake", "Healesville", "Warburton", "Alexandra", "Mansfield",
    "Halls Gap", "Ararat", "Beaufort", "Stawell", "Hamilton",
    "Bright", "Harrietville", "Mount Hotham", "Falls Creek", "Myrtleford",
    "Bruthen", "Swifts Creek", "Cann River", "Genoa",
    "Beechworth", "Marysville","Kinglake West", "Flowerdale", "Strathewen", "Toolangi", "Yea",
    "Olinda", "Mount Dandenong", "Sassafras", "Upwey", "Belgrave",
    "Lorne", "Anglesea", "Aireys Inlet", "Apollo Bay", "Forrest",
    "Horsham", "Warrnambool", "Portland", "Colac", "Casterton",
    "Benalla", "Wangaratta", "Yackandandah", "Tallangatta", "Traralgon", "Morwell", "Moe", "Churchill", "Yarram",
    "Toora", "Foster", "Leongatha", "Korumburra",
    "Sunbury", "Whittlesea", "Hurstbridge", "Warrandyte", "Geelong", "Errinundra National Park", "Snowy River National Park",
    "Alpine National Park", "Croajingolong National Park",
    "Yarra Ranges National Park", "Kinglake National Park",
    "Grampians National Park", "Wombat State Forest",
    "Bunyip State Park", "Baw Baw National Park",
]

VIC_ROUTES = [
    "Princes Highway", "Great Alpine Road", "Monash Freeway",
     "the Bonang Road", "the Cann Valley Highway", "the Buchan–Gelantipy Road", "the Dargo High Plains Road",
    "the Bogong High Plains Road",
    "the Mount Hotham Alpine Road", "the Mount Buller Road",
    "the Falls Creek Road",
    "the Mount Buffalo Road",
    "South Gippsland Highway", "Bass Highway", "Hume Freeway",
]

VIC_AGENCIES = [
    "CFA", "Country Fire Authority", "DELWP", "Emergency Management Victoria",
    "VicPolice", "Australian Federal Police", "AFAC",
    "Bureau of Meteorology", "Fire Rescue Victoria", "Victoria Police","Parks Victoria",
    "Victoria SES", "CSIRO", "National Emergency Management Agency",
]

STATISTICS = [
    "47", "83", "120", "over 200", "nearly 300", "at least 15",
    "more than 50", "hundreds of", "thousands of", "91%", "67%", "64", "12", "over 30", "at least 5", "38",
]

FACTUAL_SOURCES = [
    "Bureau of Meteorology", "CSIRO researchers",
    "Emergency Management Victoria", "CFA spokesperson",
    "fire behaviour analyst Dr Sarah Chen",
    "climate scientist Prof. James Waller",
    "AFAC report", "University of Melbourne study",
    "peer-reviewed research", "Victorian Government briefing",
    "satellite data from NASA FIRMS",
    "Bushfire and Natural Hazards CRC",
    "DELWP fire operations team",
    "Parks Victoria rangers",
]

VIC_ANIMALS = [
    "koalas", "kangaroos", "wallabies", "wombats", "possums",
    "mountain pygmy possums", "Leadbeater's possums", "gliders",
    "echidnas", "platypuses", "lyrebirds", "gang-gang cockatoos",
    "powerful owls",
]

VIC_REGIONS = [
    "East Gippsland",
    "North East Victoria",
    "Gippsland",
    "Hume",
    "Loddon Mallee",
    "Grampians",
    "Barwon South West",
    "Central",
    "Upper Murray",
    "Ovens Valley",
    "Latrobe Valley",
    "South Gippsland",
    "Yarra Ranges",
    "Macedon Ranges",
]

INFRA_TYPES = [
    # Real types of infrastructure that are damaged or disrupted during
    # Victorian bushfires — used in the infrastructure_damage cluster.
    "Telstra mobile tower",
    "NBN node",
    "Optus repeater tower",
    "telecommunications repeater",
    "emergency services radio tower",
    "power transmission line",
    "high-voltage power line",
    "AusNet substation",
    "water treatment plant",
    "rural water pumping station",
    "sewage pumping station",
    "road bridge",
    "timber bridge",
    "culvert",
    "electricity distribution pole",
    "gas pipeline access point",
    "mobile black spot tower",
    "satellite ground station",
]

INFRA_OPERATORS = [
    "Telstra", "Optus", "TPG", "Vodafone",
    "AusNet Services", "Powercor", "CitiPower",
    "VicRoads", "Local council", "Parks Victoria",
    "NBN Co", "the Victorian Government",
    "Essential Services Commission",
]


HASHTAGS_MISINFO_GENERAL = [
    "#WakeUpAustralia", "#CoverUp", "#MediaLies", "#HiddenTruth",
    "#DoYourResearch", "#TheyDontWantYouToKnow", "#FakeNews",
    "#Conspiracy", "#ShareBeforeDeleted", "#AussiePatriots",
    "#TruthBombs", "#MSMLies", "#GreatReset", "#ClimateHoax",
    "#AustraliaUncensored",
]

HASHTAGS_FACTUAL_GENERAL = [
    "#VicEmergency", "#CFA", "#BushfireSafety", "#StaySafe",
    "#EmergencyAlert", "#FireSafety", "#BushfireReady",
    "#VictoriaBushfire", "#FireDangerRating", "#EMV",
    "#BushfireRecovery", "#CommunityAlert", "#FDR",
]

HASHTAGS_BY_CLUSTER = {
    # Misinformation clusters
    "arson_conspiracy":              ["#ArsonNotClimate", "#ArsonEmergency", "#DeliberateFire", "#AussieArson", "#FireTruth"],
    "climate_change_denial":         ["#ClimateHoax", "#FuelLoads", "#PrescribedBurns", "#NotClimateChange", "#GreensFault", "#HazardReduction"],
    "false_evacuation_orders":       ["#EvacuateNow", "#LeaveNow", "#FireAlert", "#EmergencyVic", "#RoadClosed"],
    "health_misinformation":         ["#SmokeHealth", "#AirQuality", "#BigPharma", "#NaturalRemedies", "#SmokeAlert"],
    "wildlife_misinformation":       ["#SaveOurWildlife", "#KoalasCrisis", "#WildlifeGenocide", "#DonateNow", "#AussieAnimals"],
    "government_conspiracy":         ["#GovernmentCorruption", "#CFACoverUp", "#VicGovFail", "#AccountabilityNow", "#TaxpayerBetrayal"],
    "infrastructure_damage_misinfo": ["#BlackoutVic", "#TowerDown", "#NoSignal", "#InternetDown", "#CoverUp", "#InfrastructureFail"],

    # Factual clusters
    "official_fire_updates":           ["#VicEmergency", "#CFA", "#FireUpdate", "#EmergencyVic", "#EMV", "#DELWP"],
    "climate_science_communication":   ["#ClimateChange", "#BushfireScience", "#CSIRO", "#ClimateActionNow", "#FireWeather"],
    "community_preparedness":          ["#BushfireReady", "#FirePlan", "#CFA", "#PrepareActSurvive", "#KnowYourRisk"],
    "wildlife_conservation_factual":   ["#WIRES", "#WildlifeVictoria", "#KoalaRecovery", "#NativeWildlife", "#HabitatRestoration"],
    "smoke_and_health_factual":        ["#AirQualityVic", "#EPAVictoria", "#SmokeAlert", "#PM25", "#HealthAlert"],
    "infrastructure_damage_factual":   ["#VicRoads", "#RoadClosure", "#PowerOutage", "#AusNetServices", "#Telstra", "#NBNCo"],
}

"""#Section 4 : NARRATIVE CLUSTER DEFINITIONS

Each cluster is a named dictionary with:
*   "label"       → ground-truth class: "misinformation" or "factual"
* "description" →  definition of what type of theme this cluster covers or means.
 * "templates"   → sentence patterns with {placeholder} slots that get  filled with values from the word banks above.

* Placeholder tokens:
  * {location}  → specific Victorian town/place
  *  {region}    → CFA fire region
  *  {route}     → Victorian road or highway
  *  {agency}    → Victorian emergency agency
  *  {number}    → plausible statistic  
  *  {source}    → credible factual source
  *  {animal}    → Victorian native animal
  *  {infra}     → infrastructure type
  *  {operator}  → infrastructure operator/company
"""

NARRATIVE_CLUSTERS = {

    # ══════════════════════════════════════════════════════════════════════════
    #  MISINFORMATION CLUSTERS
    # ══════════════════════════════════════════════════════════════════════════

    "arson_conspiracy": {
        "label": "misinformation",
        "description": (
            "False or unverified claims that Victorian bushfires were "
            "deliberately started by coordinated arsonists, activists, or "
            "foreign agents. The dominant viral misinformation narrative "
            "during the 2019-20 Black Summer (Royal Commission, Ref [2])."
        ),
        "templates": [
            "BREAKING: {number} people arrested for deliberately lighting fires near {location} in {region}. The media won't touch this. Share before it's deleted! 🔥",
            "My cousin works at {agency} and confirmed the {location} fires were started by paid activists. Why is mainstream media ignoring this??",
            "It's not climate change — it's ARSON. {number} fires this season in {region} were deliberately lit. Do your own research 🔥🔥",
            "{agency} is covering up the real cause of the {location} fires. Professional arsonists were hired. Wake up Victoria 🇦🇺",
            "Just heard on the scanner — {agency} arrested {number} arsonists near {location} overnight and NOT ONE news outlet is reporting it. Suspicious??",
            "If climate change causes fires, why were {number} people charged with arson in {region} this week alone? I'll wait.",
            "A volunteer firefighter near {location} told me fires were deliberately lit at {number} separate points at the same time. That is coordination.",
            "Greenies are lighting fires in {region} to push their climate agenda. {number} arrests near {location} this week. Spread the truth before they censor this!!",
            "I have PROOF the {location} fire was set intentionally. {agency} is hiding it. DM me for the evidence 👀",
            "Journalist friend says {agency} has a gag order on arson arrests near {location}. {number} people in custody right now. SHARE THIS.",
        ],
    },

    "climate_change_denial": {
        "label": "misinformation",
        "description": (
            "Posts dismissing or denying the role of climate change in "
            "worsening Victorian bushfire risk. Typically attribute fires "
            "solely to arson or mismanagement, misrepresenting scientific "
            "consensus on fire-climate attribution."
        ),
        "templates": [
            "Bushfires have always happened in Victoria. Stop blaming climate change — {location} has burned before and always will. It's just nature.",
            "The {region} fires are climate propaganda. The real issue is {agency} cancelling prescribed burns, NOT your carbon footprint.",
            "Scientists said {region} would be underwater by 2020. Instead it's burning. Climate models are broken and emergency managers know it.",
            "{agency} has been caught adjusting temperature data near {location}. The fires are normal — stop the climate hysteria.",
            "My grandfather grew up near {location} and remembers fires just as severe in the 1940s. This is a natural cycle. Wake up.",
            "Climate change is a hoax. The {region} fires are caused by fuel load mismanagement — NOT emissions. Demand prescribed burns, not carbon taxes.",
            "Explain how {location} burned badly in 1939 when CO2 emissions were a fraction of today? The climate change narrative DOES NOT ADD UP.",
            "Mainstream media won't tell you that {agency} CANCELLED hazard reduction burns in {region}. That's your real cause — not your gas stove.",
            "{number} years of satellite data show no increase in global fire activity. Climate change causing Victorian bushfires? It's a political scam.",
            "The Greens blocked prescribed burns near {location} for years. But sure, blame everyday Australians. This is politics, not science.",
        ],
    },

    "false_evacuation_orders": {
        "label": "misinformation",
        "description": (
            "Fabricated or premature evacuation orders and road closures "
            "falsely attributed to Victorian emergency agencies. Extremely "
            "dangerous — causes panic, congestion on {route}, and can direct "
            "people away from safe routes. Directly documented in Ref [2]."
        ),
        "templates": [
            "URGENT ⚠️ {agency} has issued an EMERGENCY EVACUATION ORDER for {location}. Leave via {route} immediately (Unverified).",
            "SHARE THIS ⚠️ Mandatory evacuation for {location} just announced. The {agency} website is down — use {route} heading north before it's cut off!!",
            "Just got off the phone with a {agency} contact — {location} is being fully evacuated. Ignore the official app, it's not updating. Use {route}.",
            "BREAKING ⚠️ {route} CLOSED by {agency} due to fire danger near {location}. Residents in {region} stranded — government hiding the full situation.",
            "The {location} fire has EXPLODED overnight in {region}. {agency} NOT informing residents. EVACUATE NOW if you're within 20km via {route}.",
            "Do NOT travel on {route} near {location}. Fire has crossed the road in {number} spots. {agency} is not updating the app. Share this now ⚠️",
            "Someone posted an 'official' evac notice for {location}. Looks fake but sharing just in case.",
            "FAKE ALERT? Got a text saying evacuate {location} by 6pm. Is this real? Can't find official source.",
            "Is it true the whole {region} is under evacuation order? My neighbour says yes. Unverified.",
        ],
    },

    "health_misinformation": {
        "label": "misinformation",
        "description": (
            "False claims about health risks from Victorian bushfire smoke "
            "or promotion of unproven remedies. Dangerous because people "
            "may forgo genuine EPA/DHHS-recommended protection."
        ),
        "templates": [
            "Doctors won't tell you this but colloidal silver neutralises bushfire smoke toxins in your lungs. Stock up before the {location} smoke gets worse.",
            "The P2 masks {agency} is handing out in {region} are USELESS against fine particles. Use a wet cloth instead — share before this is removed.",
            "Bushfire smoke in {region} contains chemical compounds being tested on the population. That's why {agency} isn't issuing proper protection.",
            "BREAKING: hospitals near {location} are REFUSING to treat smoke inhalation to avoid public panic. A nurse told me this off the record.",
            "Vitamin C megadoses and essential oils protect your lungs from {location} smoke far better than anything {agency} recommends. Big Pharma won't say this.",
            "Real AQI near {location} is {number} times HIGHER than what {agency} publishes. They are hiding the true health risk from {region} residents.",
            "Someone I know working in emergency medicine says the {region} smoke contains {number} toxic compounds that authorities refuse to name publicly.",
            "Don't trust {agency}'s air quality readings near {location} — they don't measure the particles that are actually causing lung damage in {region}.",
        ],
    },

    "wildlife_misinformation": {
        "label": "misinformation",
        "description": (
            "Exaggerated or fabricated claims about wildlife death tolls "
            "in Victorian fires, or misleading content promoting unverified "
            "or fraudulent donation campaigns."
        ),
        "templates": [
            "SUPPRESSED: over {number} million {animal} killed in {region} fires. {agency} is hiding the real numbers to protect Victoria's tourism industry.",
            "The {animal} rescue centres near {location} are turning animals away. Donations to big charities are being pocketed — give to local private carers only.",
            "{number} {animal} found dead near {location} this week alone and it is NOT being reported. The Victorian Government doesn't care about native wildlife.",
            "A ranger near {location} told me they're quietly euthanising injured {animal} to cut costs. Your donation to major charities is funding this. Share!",
            "Scientists say the {animal} population in {region} is now FUNCTIONALLY EXTINCT due to government inaction. {number} individuals left.",
            "Footage of {animal} being rescued near {location} is being STAGED by {agency} for PR. The real toll in {region} is catastrophic and hidden.",
            "The {region} fires killed far more {animal} than {agency} is admitting — a wildlife vet told me the real number is {number} times the official figure.",
        ],
    },

    "government_conspiracy": {
        "label": "misinformation",
        "description": (
            "Conspiracy claims that Victorian government agencies deliberately "
            "mismanaged fire responses or suppressed information for ulterior "
            "motives. Distinct from legitimate criticism — alleges coordinated "
            "intentional wrongdoing with no credible evidence."
        ),
        "templates": [
            "{agency} DELIBERATELY delayed water-bombing aircraft to {location} by {number} hours. This is not incompetence — it is intentional. Demand answers.",
            "Documents show {agency} knew the {region} fires would explode and chose not to warn {location} residents. WHY?",
            "Insurance companies lobbied {agency} to let {location} burn so they could void payouts. {number} {region} families lost everything.",
            "The {location} fires conveniently destroyed land earmarked for a government development in {region}. Follow the money.",
            "{agency} is using the {region} fires as cover to pass legislation removing your rights. Don't look at the smoke — look at what they're doing in parliament.",
            "A {agency} insider told me resources were redirected from {location} to protect wealthy estates elsewhere in {region}. Poor communities were sacrificed.",
            "Why did it take {agency} {number} hours to respond to the {location} fire when aircraft were sitting idle? This was planned, not incompetence.",
        ],
    },

    "infrastructure_damage_misinfo": {
        "label": "misinformation",
        "description": (
            "False, exaggerated, or conspiratorial claims about bushfire "
            "damage to Victorian infrastructure — including telecommunications "
            "towers, power lines, roads, and bridges. May include false "
            "claims about outage scope, deliberate sabotage, or suppressed "
            "damage reports. Particularly dangerous during emergencies when "
            "people rely on accurate comms and route information."
        ),
        "templates": [
            "The {infra} near {location} was NOT damaged by the fire — it was taken down deliberately so {region} residents can't communicate. {agency} is behind this.",
            "BREAKING: {operator} has shut down ALL {infra} across {region} to prevent people sharing the truth about the {location} fires. We are being silenced.",
            "{agency} is hiding the fact that {number} {infra}s were destroyed in {region}. The real communication blackout is far worse than reported near {location}.",
            "The {infra} outage near {location} is permanent — {operator} won't rebuild in {region} for at least {number} months but they won't tell you that.",
            "My contact at {operator} says the {infra} damage near {location} will knock out communications across all of {region} for {number} weeks minimum. Prepare now.",
            "{route} near {location} is permanently CLOSED — not temporarily. {agency} and {operator} are keeping this quiet so people don't panic in {region}.",
            "The {infra} outages in {region} after the {location} fire are being used as cover to install new surveillance equipment. This is NOT a coincidence.",
            "SHARE: {operator} has quietly written off {number} {infra}s in {region} and won't replace them. Remote communities near {location} will have NO signal permanently.",
            "The bridge on {route} near {location} was structurally compromised BEFORE the fire and {agency} knew. They used the bushfire as an excuse to close it.",
            "{agency} is routing {route} repairs away from {location} to protect a developer's project in {region}. Residents will be cut off for {number} months.",
        ],
    },

    # ══════════════════════════════════════════════════════════════════════════
    #  FACTUAL CLUSTERS
    # ══════════════════════════════════════════════════════════════════════════

    "official_fire_updates": {
        "label": "factual",
        "description": (
            "Accurate, real-time updates consistent with official Victorian "
            "fire agency communications from CFA, DELWP, and EMV. These "
            "represent posts from verified agency accounts and responsible "
            "community pages."
        ),
        "templates": [
            "{agency} update for {location}: fire burning across {number} hectares in {region}. Watch-and-act warning in place. Check emergency.vic.gov.au for updates.",
            "Fire behaviour analysts at {agency} report the {location} blaze travelling northeast at {number} km/h under current wind conditions in {region}.",
            "Road closure update: {agency} has closed {route} near {location} as a precaution. Allow extra travel time and follow instructions from {agency} on site.",
            "Air quality in {location} is HAZARDOUS per EPA Victoria. {agency} advises: stay indoors, close windows, avoid outdoor physical activity in {region}.",
            "{agency} confirms {number} additional firefighting personnel deployed to {location} overnight. Water-bombing aircraft on standby at dawn for {region}.",
            "The {location} fire is at EMERGENCY warning level per {agency}. If in the impact zone in {region} and you have not left, shelter immediately — do not travel.",
            "Planned burn near {location} scheduled for next week, conditions permitting. {agency} asks {region} residents to report unplanned smoke on 1800 226 226.",
            "{agency}: the {location} fire is now 70% contained. Residents in {region} may return — check your address at emergency.vic.gov.au before travelling.",
            "Fire danger rating for {region} is EXTREME today. {agency} urges {location} residents in high-risk areas to activate their fire plan and leave early.",
            "Vic Emergency app alert: {location} fire boundary updated. Check app for latest. #VicEmergency",
            "Emergency Warning issued for {location}. Residents must leave NOW via {route}. #EmergencyWarning",
            "DFES confirms firefighters are making good progress at {location}. Stay tuned. #BushfireUpdate",
            "Incident Control Centre briefing: {location} fire 60% contained. Full containment expected within the next 24 hours."
            "{agency} has pre-positioned strike teams near {location} ahead of forecast severe weather in {region} on Thursday. Residents should prepare now.",
        ],
    },

    "climate_science_communication": {
        "label": "factual",
        "description": (
            "Accurate posts explaining scientific evidence linking climate "
            "change to increased Victorian bushfire risk, citing credible "
            "sources with measured language."
        ),
        "templates": [
            "New research from {source} confirms {location} in {region} experienced its hottest and driest spring on record — consistent with climate change projections.",
            "{source} data shows Victorian fire weather index scores have risen significantly since 1980, meaning fires ignite more easily and spread faster across {region}.",
            "CSIRO modelling: under high-emissions scenarios, extreme fire weather days in {region} could increase by up to {number}% by 2050.",
            "A {source} study found human-caused climate change made the 2019–20 Black Summer fires — including those in {region} — at least {number} times more likely.",
            "Forest ecologist from {source}: 'Fuel load management matters, but rising temperatures in {region} fundamentally change how fires like {location} behave.'",
            "{source} explains: higher temperatures dry out {region} fuel loads faster, extend the fire season into spring, and increase extreme fire weather days.",
            "Peer-reviewed study in Nature Climate Change finds a clear attribution signal linking global warming to increased fire intensity in south-east Victoria.",
            "{source} reports 2023 was the driest year on record for {region}, creating exceptional fuel conditions near {location} consistent with climate model predictions.",
        ],
    },

    "community_preparedness": {
        "label": "factual",
        "description": (
            "Practical, accurate safety advice for Victorian residents in "
            "fire-prone areas, consistent with CFA and EMV guidance."
        ),
        "templates": [
            "If you're in {location}: prepare your bushfire survival plan now. Visit cfa.vic.gov.au or call {agency} on 1800 226 226. Don't wait for fire season.",
            "Pre-season checklist for {region}: clear gutters, prepare a go-bag, and know two evacuation routes including {route}. Free templates at cfa.vic.gov.au.",
            "{agency} reminder: check your Bushfire Attack Level (BAL) rating at knowyourrisk.com.au — especially important for {location} and surrounding {region} properties.",
            "Free community workshop in {location} this Thursday run by {agency}: ember-proof vents and creating a defendable space. Register at cfa.vic.gov.au.",
            "Fire danger rating for {region} is SEVERE today. Cancel outdoor burning near {location}, keep pets indoors, have hoses connected, know your trigger to leave.",
            "Don't wait for an Emergency Warning for {location} — by then {route} may already be dangerous. Leaving early in {region} is always the safest decision.",
            "{agency} offers free home fire safety checks for {location} residents in {region}. Book at cfa.vic.gov.au or contact your local CFA brigade directly.",
            "During high fire danger near {location}: fill gutters with water, move firewood away from the house, and keep your car keys accessible in {region}.",
            "Evacuation centre open at {location}. Food and water available for residents from {region}.",
            "Local community hall in {location} accepting pets and livestock temporarily.",
            "Know the fire danger ratings for {region}: Catastrophic means leave your at-risk property near {location} the night before or early morning — do not wait.",
        ],
    },

    "wildlife_conservation_factual": {
        "label": "factual",
        "description": (
            "Accurate information about wildlife impacts from Victorian "
            "bushfires and verified rescue and rehabilitation efforts."
        ),
        "templates": [
            "{source} estimates {number} million animals were affected across Victorian fire zones including {region} — based on published habitat loss modelling.",
            "WIRES and Wildlife Victoria are coordinating {animal} rescues in {region} near {location}. Verified donation links at wildlifevictoria.org.au.",
            "Ecologists from {source} have begun post-fire fauna surveys near {location}. Early data suggests {animal} populations are recovering in canopy refuge areas.",
            "{source} explains: many {animal} survive fires in {region} by sheltering underground. The main long-term risk is habitat loss and food scarcity.",
            "Vegetation recovery in {region} is progressing, with {source} noting native regrowth near {location} providing early food sources for {animal} populations.",
            "If you find an injured {animal} near {location}, call WIRES on 1300 094 737. Do not handle native wildlife without guidance — it causes additional stress.",
            "{source} confirms post-fire recovery for {animal} populations in {region} can take 5–10 years, making long-term habitat protection near {location} critical.",
        ],
    },

    "smoke_and_health_factual": {
        "label": "factual",
        "description": (
            "Accurate public health guidance about Victorian bushfire smoke "
            "exposure, consistent with advice from EPA Victoria and the "
            "Department of Health."
        ),
        "templates": [
            "EPA Victoria: PM2.5 air quality near {location} is above safe thresholds. Use a correctly fitted P2 or N95 mask if you must go outside in {region} today.",
            "{source} advice: stay indoors with windows closed, use air conditioning on recirculate mode, and avoid exercise until {region} AQI drops below 100.",
            "People with asthma or heart conditions near {location} should follow their personal action plan and contact their GP if symptoms worsen due to {region} smoke.",
            "{agency} health alert: children, elderly, and pregnant residents in {location} are most vulnerable to fine particles. Keep them indoors today in {region}.",
            "{source} clarifies: surgical masks do NOT filter PM2.5 particles from bushfire smoke. Only a correctly fitted P2 or N95 respirator provides real protection.",
            "EPA air quality monitoring near {location} is updated hourly at epa.vic.gov.au/EPAAirWatch. Check before any outdoor activity in {region} during fire events.",
            "Smoke from the {location} fire in {region} contains fine particles and CO. {source} recommends a DIY air purifier if a commercial unit isn't available.",
        ],
    },



    "infrastructure_damage_factual": {
        "label": "factual",
        "description": (
            "Accurate, verified information about bushfire damage to Victorian "
            "infrastructure including telecommunications, power lines, roads, "
            "and bridges. Includes confirmed outages, repair timelines, and "
            "official alternative routes."
        ),
        "templates": [
            "{operator} confirms the {infra} near {location} was damaged by the {region} bushfire. Crews are on site assessing — expect {number}-day restoration timeline.",
            "{agency} update: {route} near {location} is closed due to fire damage. {operator} crews are working to assess the {infra} before the road reopens in {region}.",
            "Power outage affecting {location} in {region}: {operator} crews are working to repair fire-damaged {infra}. Check {operator}'s outage map for your address.",
            "{operator} advises mobile coverage is reduced near {location} following {infra} fire damage in {region}. Satellite devices and UHF radio recommended until repairs complete.",
            "{agency} confirms {route} near {location} will remain closed for {number} days while {operator} assesses fire-damaged {infra} in {region}. Use alternate routes.",
            "Temporary {infra} unit deployed to {location} by {operator} to restore partial coverage in {region} while permanent repairs are assessed after the bushfire.",
            "{operator} crews have restored power to {number} properties in {location} following fire damage to {infra} in {region}. Remaining properties expected online by tonight.",
            "{agency} reminds {region} residents: if your {infra} is fire-damaged near {location}, contact {operator} on their emergency line before attempting any repairs yourself.",
            "NBN Co advises {number} premises in {location} have lost service following {infra} damage in the {region} fire. Satellite backup options are available — call 1800 687 626.",
            "{route} near {location} has been inspected by VicRoads and {operator} — {infra} damage is confirmed but the road is safe for essential traffic only in {region}.",
        ],
    },
}

"""#Section 5 : Helper functions"""

# ─────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────
#Template Function
def fill_template(template):
    """
    Swap {placeholder} tokens with random values from the Victorian word banks.

    Returns:
        text             (str)       — the filled post text
        location_found   (str|None)  — specific location injected, or None
        region_found     (str|None)  — region injected, or None
        route_found      (str|None)  — road/route injected, or None
    """
    location = random.choice(VIC_LOCATIONS)
    region   = random.choice(VIC_REGIONS)
    route    = random.choice(VIC_ROUTES)
    agency   = random.choice(VIC_AGENCIES)
    number   = random.choice(STATISTICS)
    source   = random.choice(FACTUAL_SOURCES)
    animal   = random.choice(VIC_ANIMALS)
    infra    = random.choice(INFRA_TYPES)
    operator = random.choice(INFRA_OPERATORS)

    text = (template
            .replace("{location}", location)
            .replace("{region}",   region)
            .replace("{route}",    route)
            .replace("{agency}",   agency)
            .replace("{number}",   number)
            .replace("{source}",   source)
            .replace("{animal}",   animal)
            .replace("{infra}",    infra)
            .replace("{operator}", operator))

    return (
        text,
        location if "{location}" in template else None,
        region   if "{region}"   in template else None,
        route    if "{route}"    in template else None,
    )

# Hashtag FUNCTION

def build_hashtags(cluster, label):
    """
    Generate a realistic hashtag string for a post.

    Combines:
      1. Cluster-specific tags (topical precision)
      2. General misinfo or factual tags (broader signal)

    Returns a comma-separated string, e.g.:
      "#VicEmergency,#CFA,#FireUpdate,#BushfireSafety"

    WHY STORE AS COMMA-SEPARATED STRING:
    CSV cells can't hold lists natively. Comma-separated is the standard
    approach — the modelling team can split on ',' to parse them if needed.

    We pick 2–3 cluster-specific tags and 1–2 general tags, then shuffle
    so the order isn't always the same (more realistic).
    """
    cluster_tags = HASHTAGS_BY_CLUSTER.get(cluster, [])
    if label == "misinformation":
        general_tags = HASHTAGS_MISINFO_GENERAL
    else:
        general_tags = HASHTAGS_FACTUAL_GENERAL

    # Sample a realistic number of each type
    chosen_cluster  = random.sample(cluster_tags,  min(random.randint(2, 3), len(cluster_tags)))
    chosen_general  = random.sample(general_tags,  min(random.randint(1, 2), len(general_tags)))

    combined = chosen_cluster + chosen_general
    random.shuffle(combined)
    return ",".join(combined)

# Timestamp

def random_timestamp(start, end):
    """
    Return a random ISO 8601 datetime string between start and end.
    ISO 8601 format is unambiguous and understood by pandas, SQL, and APIs.
    """
    delta = end - start
    random_seconds = random.randint(0, int(delta.total_seconds()))
    ts = start + timedelta(seconds=random_seconds)
    return ts.strftime("%Y-%m-%dT%H:%M:%S")


def simulate_engagement(label):
    """
    Simulate a combined likes + shares engagement score.

    Misinformation spreads faster and further than corrections on social
    media — we encode this as a higher-mean log-normal distribution for
    misinfo (see Reference [4]). Occasional very high values reflect
    real viral spikes.
    """
    if label == "misinformation":
        raw = random.lognormvariate(mu=4.5, sigma=1.2)
    else:
        raw = random.lognormvariate(mu=3.2, sigma=0.9)
    return max(int(raw), 0)

# Username Function
def fake_username(label):
    """
    Generate a plausible fake username.
    Misinfo accounts tend toward patriotic/alarming handles.
    Factual posts tend toward named or professional handles.
    """
    if label == "misinformation":
        styles = [
            f"TrueAussie{random.randint(100, 9999)}",
            f"WakeUpVic_{random.randint(10, 999)}",
            f"RealNews{fake.last_name()}",
            f"VicPatriot{random.randint(1, 99)}",
            f"FightBack{random.randint(100, 9999)}",
            f"Hidden{fake.last_name()}Truth",
            f"AnonymousVic{random.randint(1000, 9999)}",
            f"GippyTruth{random.randint(10, 999)}",
            f"EastGippslandWatcher",
        ]
    else:
        styles = [
            f"{fake.first_name().lower()}_{fake.last_name().lower()}",
            f"{fake.last_name()}{random.randint(1, 99)}",
            f"CFA_Volunteer_{fake.last_name()}",
            f"VicBushfireWatch{random.randint(1, 50)}",
            f"Dr{fake.last_name()}{random.randint(1, 9)}",
            f"{fake.first_name()}_{random.choice(['wildlife', 'eco', 'safety', 'fire', 'gippsland'])}",
            f"PksVic_{fake.last_name()}",
        ]
    return random.choice(styles)

"""# Section 6 - Core Generation Function"""

def generate_dataset(config, clusters):
    """
    Generates the full synthetic dataset and returns a pandas DataFrame.

    Steps:
      1. Split clusters by label type.
      2. Distribute post count evenly across clusters within each label group
         (so every narrative type has equal representation).
      3. For each post: pick a random template, fill it, add all metadata.
      4. Shuffle so the CSV row order is random — important if a team member
         accidentally trains without shuffling the data themselves.
    """
    total     = config["total_posts"]
    misinfo_n = int(total * config["misinfo_ratio"])
    factual_n = total - misinfo_n

    misinfo_clusters = {k: v for k, v in clusters.items() if v["label"] == "misinformation"}
    factual_clusters = {k: v for k, v in clusters.items() if v["label"] == "factual"}

    per_misinfo = misinfo_n // len(misinfo_clusters)
    per_factual = factual_n // len(factual_clusters)

    records = []

    def generate_from_cluster(cluster_name, cluster_data, n):
        label     = cluster_data["label"]
        templates = cluster_data["templates"]
        for _ in range(n):
            template = random.choice(templates)
            text, location, region, route = fill_template(template)
            platform = random.choices(
                config["platforms"],
                weights=config["platform_weights"],
                k=1
            )[0]
            records.append({
                "post_id":            str(uuid.uuid4()),
                "text":               text,
                "cluster":            cluster_name,
                "label":              label,
                "platform":           platform,
                "region":             region,
                "location_mentioned": location,
                "route_mentioned":    route,
                "hashtags":           build_hashtags(cluster_name, label),
                "timestamp":          random_timestamp(config["date_start"], config["date_end"]),
                "engagement_score":   simulate_engagement(label),
                "username":           fake_username(label),
            })

    for name, data in misinfo_clusters.items():
        generate_from_cluster(name, data, per_misinfo)
    for name, data in factual_clusters.items():
        generate_from_cluster(name, data, per_factual)

    # Top up any posts lost to floor division
    remainder = total - len(records)
    all_names = list(clusters.keys())
    for _ in range(remainder):
        chosen = random.choice(all_names)
        generate_from_cluster(chosen, clusters[chosen], 1)

    random.shuffle(records)

    df = pd.DataFrame(records)
    return df[[
        "post_id", "text", "cluster", "label", "platform",
        "region", "location_mentioned", "route_mentioned",
        "hashtags", "timestamp", "engagement_score", "username",
    ]]

"""# Section 7 : Print Commands for Generated Dataset Summary"""

def print_summary(df):
    """
    Readable summary of the generated dataset.
    Screenshot this for your Sprint 2 demo or handover notes.
    """
    print("\n" + "═" * 64)
    print("  FIREFUSION SYNTHETIC DATASET — GENERATION SUMMARY")
    print("═" * 64)
    print(f"  Total posts:  {len(df):,}")
    print(f"  Columns:      {list(df.columns)}\n")

    print("  LABEL SPLIT")
    for label, count in df["label"].value_counts().items():
        pct = count / len(df) * 100
        bar = "█" * int(pct / 2)
        print(f"    {label:<18} {count:>5,}  ({pct:5.1f}%)  {bar}")

    print("\n  POSTS PER CLUSTER")
    for cluster, label_val in df.groupby("cluster")["label"].first().items():
        n   = len(df[df["cluster"] == cluster])
        tag = "[MISINFO]" if label_val == "misinformation" else "[FACTUAL]"
        print(f"    {tag} {cluster:<44} {n:>4}")

    print("\n  PLATFORM DISTRIBUTION")
    for platform, count in df["platform"].value_counts().items():
        pct = count / len(df) * 100
        print(f"    {platform:<15} {count:>5,}  ({pct:5.1f}%)")

    print("\n  TOP REGIONS MENTIONED")
    region_counts = df["region"].dropna().value_counts().head(8)
    for region, count in region_counts.items():
        print(f"    {region:<35} {count:>4}")

    print("\n  ENGAGEMENT (mean) by label")
    print(df.groupby("label")["engagement_score"].mean().round(1).to_string())

    print("\n  SAMPLE POSTS + HASHTAGS (1 per cluster)")
    for cluster in sorted(df["cluster"].unique()):
        row     = df[df["cluster"] == cluster].sample(1, random_state=SEED).iloc[0]
        tag     = "MISINFO" if row["label"] == "misinformation" else "FACTUAL"
        preview = row["text"][:100] + ("..." if len(row["text"]) > 100 else "")
        print(f"\n  [{tag}] {cluster}")
        print(f"    {preview}")
        print(f"    Tags: {row['hashtags']}")

    print("\n" + "═" * 64)

"""#Section 8 : Generate Sythetic Data"""

def main():
    print("\n🔥 FireFusion — Synthetic Data Generator")
    print("   Sprint 2 | Victoria-Centric Narrative Cluster Generation\n")

    print("  Generating posts...")
    df = generate_dataset(CONFIG, NARRATIVE_CLUSTERS)
    print(f"  ✅ {len(df):,} posts generated across {df['cluster'].nunique()} clusters.\n")

    print_summary(df)

    output = CONFIG["output_file"]
    df.to_csv(output, index=False, encoding="utf-8")
    print(f"\n  💾 Saved → {output}")
    print(f"     {len(df):,} rows  |  {len(df.columns)} columns")
    print("\n  In Google Colab: open the 📁 Files panel (left sidebar) to download.\n")
    print("  ── HANDOVER NOTES FOR THE MODELLING TEAM ──────────────────────────")
    print("  • Primary features for text classification: 'text' and 'label'")
    print("  • 'cluster' = fine-grained narrative type (13 categories)")
    print("  • 'hashtags' = comma-separated tags, split on ',' to use as features")
    print("  • 'region', 'location_mentioned', 'route_mentioned' = geo metadata")
    print("  • 'engagement_score' = optional numeric metadata feature")
    print("  • Class split: 60% misinformation / 40% factual — use F1, not accuracy")
    print("  • Seed: 42 — re-run this script to reproduce identical data")
    print("  ────────────────────────────────────────────────────────────────────\n")


if __name__ == "__main__":
    main()

"""# References
[1] Bondielli & Marcelloni (2019). A survey on fake news and rumour detection techniques. Information Sciences, 497, 38–55.

Link: https://doi.org/10.1016/j.ins.2019.05.035

[2] Australian Government (2020). Royal Commission into National Natural Disaster Arrangements — Report. Commonwealth of Australia.

Link: https://www.royalcommission.gov.au/system/files/2020-12/Royal%20Commission%20into%20National%20Natural%20Disaster%20Arrangements%20-%20Report%20%20%5Baccessible%5D.pdf


[3] Sharma et al. (2019). Combating fake news. ACM TIST, 10(3), 1–42.
   Link: https://doi.org/10.1145/3305260

[4] Shu et al. (2020). FakeNewsNet. Big Data, 8(3), 171–188.
   Link: https://doi.org/10.1089/big.2020.0062

"""